# resources:
    # This is how we would reference a template from a different repository
  # repositories:
  #   - repository: templates
  #     type: git
  #     name: azure-pipelines-templates
  #     ref: refs/tags/v1.0.0

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
      - TODO.md
      - LICENSE
      - .gitignore
      - .gitattributes
      - .vscode
      - .github
      - .azure-pipelines
      - .git
      - ./docs

resources:
  repositories:
    - repository: templates
      type: github
      name: rbleattler/az-pipelines-common-templates

steps:
  - template: /.azure-pipelines/set-version-date.yml@templates
  - template: /.azure-pipelines/build-dotnetcore.yml@templates
    parameters:
      slnFile: 'ConfigToRegex.sln'
      buildConfiguration: 'Release'
      sdkVersion: '8.x'
      publishWebProjects: false
      tests:
        - tests/ConfigToRegexTests/ConfigToRegexTests.csproj

